spring:
  application:
    name: USER-SERVICE

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

      register-with-eureka: false # Регистрация с Eureka
      fetch-registry: false # Получение информации о других сервисах